name: Generate Sitemap

on:
  push:
    branches: [ main ]

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm clean-install
      
    - name: Generate sitemap
      run: npm run generate-sitemap
